# Generated by Django 4.1 on 2024-02-27 08:25

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', froala_editor.fields.FroalaField()),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(default='Tutoriel', max_length=200)),
            ],
        ),
    ]
